create table person (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	gender VARCHAR(50),
	date_of_birth DATE,
	email VARCHAR(50),
	country_of_birth VARCHAR(50)
);
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Remy', 'Kienl', 'Female', '2024-07-04', 'rkienl0@berkeley.edu', null);
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Fonz', 'Aguirrezabala', 'Male', '2025-01-12', 'faguirrezabala1@aboutads.info', 'Nigeria');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Rikki', 'Sibborn', 'Male', '2024-10-13', 'rsibborn2@wix.com', 'Panama');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Sonya', 'MacCoughen', 'Female', '2024-09-07', null, 'Russia');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Glory', 'Sollis', 'Female', '2024-11-30', 'gsollis4@techcrunch.com', null);
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Debra', 'McNay', 'Female', '2024-06-13', 'dmcnay5@altervista.org', null);
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Beckie', 'Kropp', 'Female', '2024-05-17', null, 'Macedonia');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Erny', 'Southerns', 'Male', '2024-10-09', null, 'Argentina');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Putnem', 'Alfonsini', 'Male', '2025-03-01', 'palfonsini8@bloomberg.com', null);
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Nissy', 'MacQuarrie', 'Non-binary', '2024-08-22', 'nmacquarrie9@guardian.co.uk', 'Philippines');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Deane', 'Pryor', 'Female', '2024-10-28', 'dpryora@sina.com.cn', 'Nepal');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Tedmund', 'Guilloton', 'Male', '2025-01-07', 'tguillotonb@yandex.ru', 'Serbia');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Reggie', 'Bertelsen', 'Non-binary', '2024-10-16', null, 'China');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Morse', 'Oakland', 'Male', '2024-09-22', 'moaklandd@usnews.com', 'China');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Herbert', 'Pendlebery', 'Male', '2024-08-29', null, 'Greece');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Sutton', 'Addyman', 'Male', '2024-12-23', 'saddymanf@rambler.ru', 'Palestinian Territory');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Agnesse', 'Whitehouse', 'Female', '2024-06-22', null, 'Philippines');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Lizette', 'Clausen', 'Female', '2024-08-05', null, 'Norway');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Kerstin', 'Vreede', 'Female', '2024-06-14', null, null);
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Marnia', 'Furlow', 'Female', '2025-01-31', 'mfurlowj@skype.com', null);
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Gianni', 'Bubeer', 'Male', '2024-05-19', null, 'Kazakhstan');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Boony', 'Wotton', 'Male', '2024-08-27', 'bwottonl@seesaa.net', 'Panama');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Pauli', 'Keedy', 'Female', '2025-02-10', 'pkeedym@yellowpages.com', null);
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Octavia', 'Leisman', 'Female', '2024-04-13', null, null);
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Fitzgerald', 'Crowd', 'Male', '2024-08-11', 'fcrowdo@dyndns.org', 'China');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Antin', 'Hallex', 'Male', '2025-03-17', null, 'Pakistan');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Rita', 'Matusson', 'Female', '2024-09-12', 'rmatussonq@utexas.edu', null);
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Saba', 'Selvester', 'Female', '2025-01-23', 'sselvesterr@usgs.gov', null);
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Gabi', 'Haggarth', 'Female', '2024-06-03', 'ghaggarths@spotify.com', 'Armenia');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Lucina', 'Vogele', 'Female', '2025-03-03', 'lvogelet@cnbc.com', 'China');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Estel', 'Farrall', 'Female', '2024-10-17', null, 'Portugal');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Elnar', 'Romans', 'Male', '2024-08-10', 'eromansv@w3.org', 'Nigeria');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Gamaliel', 'Afield', 'Male', '2025-02-07', 'gafieldw@vk.com', 'Ukraine');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Meir', 'Bown', 'Male', '2024-05-06', 'mbownx@w3.org', 'China');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Milka', 'Taw', 'Female', '2024-11-12', 'mtawy@soundcloud.com', 'United States');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Wilma', 'Greensted', 'Female', '2024-06-02', 'wgreenstedz@jimdo.com', 'Ukraine');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Cacilie', 'Blincko', 'Non-binary', '2024-08-17', 'cblincko10@globo.com', 'China');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Davidson', 'Paulazzi', 'Male', '2024-08-03', 'dpaulazzi11@marketwatch.com', null);
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Shep', 'Esterbrook', 'Male', '2025-01-23', 'sesterbrook12@cargocollective.com', 'China');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Elvera', 'Cruz', 'Female', '2024-12-30', 'ecruz13@addthis.com', null);
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Gilberta', 'Llorente', 'Female', '2025-03-18', 'gllorente14@ifeng.com', null);
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Marga', 'Calbreath', 'Female', '2024-07-07', 'mcalbreath15@state.tx.us', null);
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Garner', 'Rylett', 'Genderqueer', '2025-02-27', 'grylett16@samsung.com', 'Russia');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Austen', 'Puckey', 'Male', '2025-03-18', null, null);
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Estele', 'Braga', 'Female', '2024-06-03', 'ebraga18@japanpost.jp', null);
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Bari', 'Drinkeld', 'Female', '2024-11-17', 'bdrinkeld19@g.co', null);
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Flossie', 'Hulcoop', 'Female', '2025-03-01', null, 'Colombia');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Mattie', 'Jeffcoat', 'Non-binary', '2025-04-05', 'mjeffcoat1b@ifeng.com', null);
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Kym', 'Jakubowsky', 'Genderfluid', '2025-04-11', 'kjakubowsky1c@t.co', 'Philippines');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Ben', 'Lindenblatt', 'Male', '2024-12-23', 'blindenblatt1d@businessweek.com', 'Chad');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Rustin', 'Landell', 'Male', '2025-01-12', 'rlandell1e@blogspot.com', 'Afghanistan');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Faythe', 'D''Avaux', 'Polygender', '2024-09-01', null, null);
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Bondie', 'Ducker', 'Polygender', '2024-10-26', null, 'Bosnia and Herzegovina');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Thorvald', 'Wagenen', 'Male', '2025-03-22', null, 'Peru');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Brewster', 'Hakeworth', 'Male', '2024-10-03', 'bhakeworth1i@bloomberg.com', null);
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Ilyse', 'Jendrach', 'Female', '2025-01-03', 'ijendrach1j@meetup.com', 'Brazil');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Zack', 'Cicchelli', 'Male', '2025-03-16', 'zcicchelli1k@wikispaces.com', 'China');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Othello', 'Allix', 'Male', '2024-10-12', null, 'Japan');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Georgeanne', 'Lazare', 'Female', '2024-11-08', null, 'Philippines');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Gilligan', 'Durston', 'Agender', '2024-10-01', 'gdurston1n@paypal.com', null);
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Rockie', 'Truce', 'Male', '2024-11-13', null, 'United States');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Huberto', 'Tremelling', 'Male', '2024-06-17', 'htremelling1p@usda.gov', 'Czech Republic');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Whittaker', 'Wildt', 'Male', '2024-06-21', 'wwildt1q@hugedomains.com', 'Ukraine');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Nike', 'Aucutt', 'Non-binary', '2024-04-30', null, null);
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Nealson', 'McGeorge', 'Male', '2024-10-22', null, 'France');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Umeko', 'Melin', 'Female', '2024-11-11', 'umelin1t@a8.net', 'Russia');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Jareb', 'Colebrook', 'Genderqueer', '2025-03-23', 'jcolebrook1u@sourceforge.net', null);
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Chris', 'Gullifant', 'Non-binary', '2025-02-04', 'cgullifant1v@prweb.com', 'Malaysia');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Rocky', 'Becke', 'Male', '2024-04-23', 'rbecke1w@people.com.cn', 'Canada');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Ludwig', 'Fulleylove', 'Male', '2024-06-21', 'lfulleylove1x@youtu.be', 'Russia');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Vince', 'McMeanma', 'Male', '2024-08-19', null, 'China');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Sophia', 'Dominichetti', 'Agender', '2024-11-26', 'sdominichetti1z@accuweather.com', null);
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Cross', 'Kingscote', 'Male', '2024-06-28', 'ckingscote20@netlog.com', 'China');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Danella', 'Ridhole', 'Female', '2024-12-01', 'dridhole21@sogou.com', 'Kosovo');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Jacynth', 'Burgne', 'Female', '2024-10-01', null, 'China');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Kevyn', 'Blofeld', 'Female', '2025-03-10', null, 'Bolivia');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Abbey', 'Pittet', 'Male', '2024-05-02', 'apittet24@google.com.au', 'Peru');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Loria', 'O''Calleran', 'Female', '2025-04-04', null, null);
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Gwendolin', 'Eyer', 'Female', '2024-04-22', 'geyer26@php.net', 'Brazil');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Basile', 'Newick', 'Male', '2024-09-19', 'bnewick27@toplist.cz', null);
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Thelma', 'Cheine', 'Female', '2024-10-25', null, null);
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Dulce', 'Croome', 'Female', '2024-08-26', null, 'China');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Malorie', 'Bulfit', 'Bigender', '2025-03-26', 'mbulfit2a@imdb.com', 'Philippines');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Far', 'Gailor', 'Male', '2025-01-17', 'fgailor2b@mit.edu', null);
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Sawyer', 'Crichmer', 'Male', '2024-06-14', null, 'Mauritius');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Filide', 'Petrushka', 'Female', '2024-06-25', 'fpetrushka2d@qq.com', null);
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Burtie', 'De Carteret', 'Male', '2024-11-21', 'bdecarteret2e@free.fr', null);
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Nicolette', 'Prandi', 'Female', '2024-12-15', 'nprandi2f@statcounter.com', null);
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Donny', 'Boarer', 'Bigender', '2024-11-12', 'dboarer2g@shareasale.com', 'Peru');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Donica', 'Standell', 'Genderfluid', '2024-12-22', 'dstandell2h@usda.gov', 'Indonesia');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Ariela', 'Rawsthorn', 'Female', '2025-01-14', null, null);
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Baxy', 'MacGillicuddy', 'Male', '2024-12-05', 'bmacgillicuddy2j@flavors.me', 'China');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Blake', 'Arpe', 'Male', '2024-10-03', 'barpe2k@baidu.com', 'United States');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Pooh', 'Wrates', 'Male', '2024-04-29', null, 'China');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Ingemar', 'Aries', 'Male', '2024-08-01', null, 'Peru');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Carny', 'Wedmore.', 'Male', '2024-09-03', null, 'Albania');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Lenci', 'Kaesmans', 'Male', '2024-08-16', 'lkaesmans2o@ameblo.jp', 'Peru');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Louie', 'Masham', 'Male', '2024-09-02', null, null);
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Brendin', 'Curd', 'Male', '2024-09-07', 'bcurd2q@omniture.com', 'Indonesia');
insert into person (first_name, last_name, gender, date_of_birth, email, country_of_birth) values ('Selestina', 'Skoate', 'Female', '2025-02-05', null, null);